/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nabilla Febry
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtpetugas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtresi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnopol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtkendaraan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txthari = new javax.swing.JTextField();
        tglkeluar = new com.toedter.calendar.JDateChooser();
        tglmasuk = new com.toedter.calendar.JDateChooser();
        txtharga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PARKIR");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(310, 20, 140, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 800, 90);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nama Petugas");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 11, 140, 14);
        jPanel2.add(txtpetugas);
        txtpetugas.setBounds(10, 30, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("No. Resi");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 70, 130, 14);
        jPanel2.add(txtresi);
        txtresi.setBounds(10, 90, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("No. Polisi");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 130, 140, 14);
        jPanel2.add(txtnopol);
        txtnopol.setBounds(10, 150, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jenis Kendaraan");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 190, 120, 14);
        jPanel2.add(txtkendaraan);
        txtkendaraan.setBounds(10, 210, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tanggal Masuk");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 250, 120, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tanggal Keluar");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 310, 120, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Jumlah hari");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 370, 120, 14);

        txthari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthariActionPerformed(evt);
            }
        });
        jPanel2.add(txthari);
        txthari.setBounds(10, 390, 150, 30);
        jPanel2.add(tglkeluar);
        tglkeluar.setBounds(10, 330, 150, 30);
        jPanel2.add(tglmasuk);
        tglmasuk.setBounds(10, 270, 150, 30);
        jPanel2.add(txtharga);
        txtharga.setBounds(10, 450, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Harga");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 430, 120, 14);

        jButton4.setText("Total");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(180, 450, 57, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 110, 280, 490);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(10, 10, 80, 23);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(110, 10, 80, 23);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(210, 10, 80, 23);

        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(310, 10, 80, 23);

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(410, 10, 80, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(300, 110, 510, 40);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "namapetugas", "noresi", "nopol", "jeniskendaraan", "tanggalmasuk", "tanggalkeluar", "jumlahhari", "harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 490, 350);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 160, 510, 440);

        setSize(new java.awt.Dimension(833, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String masuk = dateFormat.format(tglmasuk.getDate());
        String keluar = dateFormat.format(tglkeluar.getDate());
        
        if (txtpetugas.getText().equals("") || 
                txtresi.getText().equals("") ||
                txtnopol.getText().equals("") || 
                txtkendaraan.getText().equals("") ||
                txthari.getText().equals("") ||
                txtharga.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        else
        {
            String SQL = "INSERT INTO tb_transaksi VALUES ('"+txtpetugas.getText()
                    +"', '"+txtresi.getText()
                    +"', '"+txtnopol.getText()
                    +"', '"+txtkendaraan.getText()
                    +"', '"+masuk+"', '"+keluar
                    +"', '"+txthari.getText()
                    +"', '"+txtharga.getText()+"')";
            
            int status = KoneksiDB.execute(SQL);
                
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int baris = tblData.getSelectedRow();

        if (baris != -1)
        {
            String noresi = tblData.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM t_siswa WHERE noresi='"+noresi+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }

        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtpetugas.setText("");
        txtresi.setText("");
        txtnopol.setText("");
        txtkendaraan.setText("");
        tglmasuk.setDate(null);
        tglkeluar.setDate(null);
        txthari.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        MessageFormat header = new MessageFormat("Transaksi Parkir");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");

        try
        {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txthariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthariActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int hari = Integer.parseInt(txthari.getText().toString());
        
        int harga = hari*3000;
        txtharga.setText(""+harga);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        selectData();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        
        
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tglkeluar;
    private com.toedter.calendar.JDateChooser tglmasuk;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthari;
    private javax.swing.JTextField txtkendaraan;
    private javax.swing.JTextField txtnopol;
    private javax.swing.JTextField txtpetugas;
    private javax.swing.JTextField txtresi;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"namapetugas","noresi","nopolisi","jeniskendaraan","tanggalmasuk","tanggalkeluar", "jumlahhari", "harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while(rs.next())
            {
                String namapetugas = rs.getString(1);
                String noresi = rs.getString(2);
                String nopolisi = rs.getString(3);
                String jeniskendaraan = rs.getString(4);
                String tanggalmasuk = rs.getString(5);
                String tanggalkeluar = rs.getString(6);
                String jumlahhari = rs.getString(7);
                String harga = rs.getString(8);
                String data[] = {namapetugas, noresi, nopolisi, jeniskendaraan, tanggalmasuk, tanggalkeluar, jumlahhari, harga};
                dtm.addRow(data);
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
